# Generated by Django 5.2.6 on 2025-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='jenis_buah',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
